name: feastly
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <3.12.0'

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_riverpod: ^2.3.0
  flutter_screenutil: ^5.7.0
  freezed_annotation: ^2.2.0
  go_router: ^7.0.1
  google_fonts: ^4.0.3
  introduction_screen: ^3.1.6
  json_annotation: ^4.8.0
  pinput: ^2.2.31
  riverpod_annotation: ^2.0.1
  keyboard_dismisser: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_card_swiper: ^5.0.0
  share_plus: ^7.0.0
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.4
  image_picker: ^0.8.7+2
  image_cropper: ^4.0.1
  dio: ^5.1.1
  flutter_secure_storage: ^8.0.0
  envied: ^0.3.0+3
  vector_graphics: ^1.1.5+1
  flutter_blurhash: ^0.7.0
  flutter_markdown: ^0.6.15
  form_builder_validators: ^9.0.0
  url_launcher: ^6.1.11
  http_parser: ^4.0.2
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^14.1.1
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  custom_lint: ^0.4.0
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  envied_generator: ^0.3.0+3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/fonts/
    - google_fonts/
  
  fonts:
    - family:  FeastlyIcon
      fonts:
        - asset: assets/fonts/FeastlyIcon.ttf
