name: feastly
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_riverpod: ^2.3.0
  go_router: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_native_splash:
  color: "#59D1CA"
  image: assets/images/feastly_logo.png

  android_12:

flutter_icons:
  android: true
  image_path: "assets/images/feastly_icon.png"
  adaptive_icon_background: "#59D1CA"
  adaptive_icon_foreground: "assets/images/feastly_icon.png"
  ios: true
  min_sdk_android: 21
