name: feastly
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_riverpod: ^2.3.0
  flutter_screenutil: ^5.7.0
  freezed_annotation: ^2.2.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  introduction_screen: ^3.1.6
  json_annotation: ^4.8.0
  pinput: ^2.2.31
  riverpod_annotation: ^2.0.1
  keyboard_dismisser: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_card_swiper:
    git:
      url: https://github.com/ricardodalarme/flutter_card_swiper.git
      ref: feat/custom-card-offset
  share_plus: ^6.3.1
  flutter_slidable: ^2.0.0
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  custom_lint: ^0.3.2
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5
  json_serializable: ^6.6.1
  freezed: ^2.3.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  
  fonts:
    - family:  FeastlyIcon
      fonts:
        - asset: assets/fonts/FeastlyIcon.ttf
