/// Flutter icons FeastlyIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FeastlyIcon
///      fonts:
///       - asset: fonts/FeastlyIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FeastlyIcon {
  FeastlyIcon._();

  static const _kFontFam = 'FeastlyIcon';
  static const String? _kFontPkg = null;

  static const IconData button_arrow_down = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData button_arrow_right = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData button_close = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData button_copy = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData button_recipe_inactive = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData button_restaurant_inactive = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_code = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_distance = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_edit = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_email = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_hide_eye = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_padlock = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_user = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users_alt = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_delete = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uil_plus = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector_3 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back_green = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData button_radio_deselected = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData button_radio_selected = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData button_arrow_left = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData button_recipe_inactive_1 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_alt = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_go_back = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData button_setting_mudassir = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
